### ISSUE TITLE
[polyglot-clojure] clojure JAR not found on classpath when running Maven targets

### ISSUE THREAD

**Issue by lwiechec** [takari/polyglot-maven#117]
Hi,

big thanks for the polyglot maven project! I got excited as I have seen that Clojure is supported so I quickly created a [pom.clj](https://gist.github.com/lwiechec/96395b715bde4ac4305628058400156a) file.

I have also created extension.xml file in .mvn in project's root:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<extensions>
  <extension>
    <groupId>io.takari.polyglot</groupId>
    <artifactId>polyglot-clojure</artifactId>
    <version>0.1.19</version>
  </extension>
</extensions>
```

However, I am getting following error:

```
mvn -X compile
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/luke/work/tools/apache-maven
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /home/luke/work/jdk/jdk1.8.0_112/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.8-040408-generic", arch: "amd64", family: "unix"
[DEBUG] Reading global settings from /home/luke/work/tools/apache-maven/conf/settings.xml
[DEBUG] Reading user settings from /home/luke/.m2/settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/luke/.m2/repository
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=3, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=3, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=3, DefaultDependencyCollector.collectTime=91, DefaultDependencyCollector.transformTime=6}
[DEBUG] io.takari.polyglot:polyglot-clojure:jar:0.1.19:
[DEBUG]    io.takari.polyglot:polyglot-common:jar:0.1.19:compile
[DEBUG]    org.clojure:clojure:jar:1.1.0:compile
[DEBUG] Populating class realm coreExtension>io.takari.polyglot:polyglot-clojure:0.1.19
[DEBUG]   Included /home/luke/.m2/repository/io/takari/polyglot/polyglot-clojure/0.1.19/polyglot-clojure-0.1.19.jar
[DEBUG]   Included /home/luke/.m2/repository/io/takari/polyglot/polyglot-common/0.1.19/polyglot-common-0.1.19.jar
[DEBUG]   Included /home/luke/.m2/repository/org/clojure/clojure/1.1.0/clojure-1.1.0.jar
[DEBUG] Populating class realm maven.ext
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < maven.ext
[DEBUG]   Imported: javax.enterprise.util.* < maven.ext
[DEBUG]   Imported: javax.inject.* < maven.ext
[DEBUG]   Imported: org.apache.maven.* < maven.ext
[DEBUG]   Imported: org.apache.maven.artifact < maven.ext
[DEBUG]   Imported: org.apache.maven.classrealm < maven.ext
[DEBUG]   Imported: org.apache.maven.cli < maven.ext
[DEBUG]   Imported: org.apache.maven.configuration < maven.ext
[DEBUG]   Imported: org.apache.maven.exception < maven.ext
[DEBUG]   Imported: org.apache.maven.execution < maven.ext
[DEBUG]   Imported: org.apache.maven.execution.scope < maven.ext
[DEBUG]   Imported: org.apache.maven.lifecycle < maven.ext
[DEBUG]   Imported: org.apache.maven.model < maven.ext
[DEBUG]   Imported: org.apache.maven.monitor < maven.ext
[DEBUG]   Imported: org.apache.maven.plugin < maven.ext
[DEBUG]   Imported: org.apache.maven.profiles < maven.ext
[DEBUG]   Imported: org.apache.maven.project < maven.ext
[DEBUG]   Imported: org.apache.maven.reporting < maven.ext
[DEBUG]   Imported: org.apache.maven.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.rtinfo < maven.ext
[DEBUG]   Imported: org.apache.maven.settings < maven.ext
[DEBUG]   Imported: org.apache.maven.toolchain < maven.ext
[DEBUG]   Imported: org.apache.maven.usability < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.* < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authentication < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authorization < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.events < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.observers < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.proxy < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.resource < maven.ext
[DEBUG]   Imported: org.codehaus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.* < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.component < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.configuration < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.container < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.context < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.logging < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.personality < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.* < maven.ext
[DEBUG]   Imported: org.eclipse.aether.artifact < maven.ext
[DEBUG]   Imported: org.eclipse.aether.collection < maven.ext
[DEBUG]   Imported: org.eclipse.aether.deployment < maven.ext
[DEBUG]   Imported: org.eclipse.aether.graph < maven.ext
[DEBUG]   Imported: org.eclipse.aether.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.installation < maven.ext
[DEBUG]   Imported: org.eclipse.aether.internal.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.metadata < maven.ext
[DEBUG]   Imported: org.eclipse.aether.repository < maven.ext
[DEBUG]   Imported: org.eclipse.aether.resolution < maven.ext
[DEBUG]   Imported: org.eclipse.aether.spi < maven.ext
[DEBUG]   Imported: org.eclipse.aether.transfer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.version < maven.ext
[DEBUG]   Imported: org.slf4j.* < maven.ext
[DEBUG]   Imported: org.slf4j.helpers.* < maven.ext
[DEBUG]   Imported: org.slf4j.spi.* < maven.ext
[DEBUG]   Imported: org.sonatype.maven.polyglot < maven.ext
[DEBUG]   Imported: org.sonatype.maven.polyglot.execute < maven.ext
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /home/luke/work/tools/apache-maven/conf/settings.xml
[DEBUG] Reading user settings from /home/luke/.m2/settings.xml
[DEBUG] Reading global toolchains from /home/luke/work/tools/apache-maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/luke/.m2/toolchains.xml
[DEBUG] Using local repository at /home/luke/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/luke/.m2/repository
[INFO] Scanning for projects...
[DEBUG] /home/luke/work/projects/csd-publisher/.polyglot.pom.clj
---------------------------------------------------
constituent[0]: file:/home/luke/work/tools/apache-maven/lib/maven-model-3.3.9.jar
constituent[1]: file:/home/luke/work/tools/apache-maven/lib/maven-aether-provider-3.3.9.jar
constituent[2]: file:/home/luke/work/tools/apache-maven/lib/maven-embedder-3.3.9.jar
constituent[3]: file:/home/luke/work/tools/apache-maven/lib/maven-repository-metadata-3.3.9.jar
constituent[4]: file:/home/luke/work/tools/apache-maven/lib/org.eclipse.sisu.inject-0.3.2.jar
constituent[5]: file:/home/luke/work/tools/apache-maven/lib/wagon-provider-api-2.10.jar
constituent[6]: file:/home/luke/work/tools/apache-maven/lib/plexus-sec-dispatcher-1.3.jar
constituent[7]: file:/home/luke/work/tools/apache-maven/lib/guice-4.0-no_aop.jar
constituent[8]: file:/home/luke/work/tools/apache-maven/lib/maven-compat-3.3.9.jar
constituent[9]: file:/home/luke/work/tools/apache-maven/lib/jsr250-api-1.0.jar
constituent[10]: file:/home/luke/work/tools/apache-maven/lib/guava-18.0.jar
constituent[11]: file:/home/luke/work/tools/apache-maven/lib/slf4j-api-1.7.5.jar
constituent[12]: file:/home/luke/work/tools/apache-maven/lib/maven-artifact-3.3.9.jar
constituent[13]: file:/home/luke/work/tools/apache-maven/lib/maven-builder-support-3.3.9.jar
constituent[14]: file:/home/luke/work/tools/apache-maven/lib/javax.inject-1.jar
constituent[15]: file:/home/luke/work/tools/apache-maven/lib/slf4j-simple-1.7.5.jar
constituent[16]: file:/home/luke/work/tools/apache-maven/lib/plexus-cipher-1.7.jar
constituent[17]: file:/home/luke/work/tools/apache-maven/lib/maven-settings-builder-3.3.9.jar
constituent[18]: file:/home/luke/work/tools/apache-maven/lib/commons-lang3-3.4.jar
constituent[19]: file:/home/luke/work/tools/apache-maven/lib/aopalliance-1.0.jar
constituent[20]: file:/home/luke/work/tools/apache-maven/lib/aether-impl-1.0.2.v20150114.jar
constituent[21]: file:/home/luke/work/tools/apache-maven/lib/plexus-utils-3.0.22.jar
constituent[22]: file:/home/luke/work/tools/apache-maven/lib/maven-core-3.3.9.jar
constituent[23]: file:/home/luke/work/tools/apache-maven/lib/aether-spi-1.0.2.v20150114.jar
constituent[24]: file:/home/luke/work/tools/apache-maven/lib/maven-model-builder-3.3.9.jar
constituent[25]: file:/home/luke/work/tools/apache-maven/lib/maven-plugin-api-3.3.9.jar
constituent[26]: file:/home/luke/work/tools/apache-maven/lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[27]: file:/home/luke/work/tools/apache-maven/lib/commons-cli-1.2.jar
constituent[28]: file:/home/luke/work/tools/apache-maven/lib/plexus-interpolation-1.21.jar
constituent[29]: file:/home/luke/work/tools/apache-maven/lib/aether-util-1.0.2.v20150114.jar
constituent[30]: file:/home/luke/work/tools/apache-maven/lib/commons-io-2.2.jar
constituent[31]: file:/home/luke/work/tools/apache-maven/lib/wagon-file-2.10.jar
constituent[32]: file:/home/luke/work/tools/apache-maven/lib/wagon-http-2.10-shaded.jar
constituent[33]: file:/home/luke/work/tools/apache-maven/lib/aether-api-1.0.2.v20150114.jar
constituent[34]: file:/home/luke/work/tools/apache-maven/lib/commons-lang-2.6.jar
constituent[35]: file:/home/luke/work/tools/apache-maven/lib/plexus-component-annotations-1.6.jar
constituent[36]: file:/home/luke/work/tools/apache-maven/lib/wagon-http-shared-2.10.jar
constituent[37]: file:/home/luke/work/tools/apache-maven/lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[38]: file:/home/luke/work/tools/apache-maven/lib/cdi-api-1.0.jar
constituent[39]: file:/home/luke/work/tools/apache-maven/lib/jsoup-1.7.2.jar
constituent[40]: file:/home/luke/work/tools/apache-maven/lib/org.eclipse.sisu.plexus-0.3.2.jar
constituent[41]: file:/home/luke/work/tools/apache-maven/lib/maven-settings-3.3.9.jar
constituent[42]: file:/home/luke/work/tools/apache-maven/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.sonatype.maven.polyglot.clojure.ClojureModelReader.read(ClojureModelReader.java:42)
	at org.sonatype.maven.polyglot.io.ModelReaderSupport.read(ModelReaderSupport.java:48)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:114)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:95)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate clojure/core__init.class or clojure/core.clj on classpath: 
	at clojure.lang.RT.<clinit>(RT.java:295)
	... 27 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class or clojure/core.clj on classpath: 
	at clojure.lang.RT.load(RT.java:402)
	at clojure.lang.RT.load(RT.java:371)
	at clojure.lang.RT.doInit(RT.java:406)
	at clojure.lang.RT.<clinit>(RT.java:292)
	... 27 more
```

from what I can see, clojure 1.1.0 JAR _is_ included. Can't understand why the class is not found?...

**Comment by mosabua** [comment]
If you have clojure source you still need to add a dependency to that .. plugin execution and dependency/compile classpath are separate
