### ISSUE TITLE
[polyglot-yaml] Failure to parse mojo configuration list items

### ISSUE THREAD

**Issue by Tzrlk** [takari/polyglot-maven#151]
I've been trying to get CDI working with my kotlin project, and this forced me to use the `kotlin-plugin-allopen` extension. Unfortunately, when I run the execution, the following stacktrace is provided:

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.1.51:compile (compile) on project: Unable to parse configuration of mojo org.jetbrains.kotlin:kotlin-maven-plugin:1.1.51:compile for parameter pluginOption: Cannot create instance of class org.jetbrains.kotlin.maven.PluginOption: org.jetbrains.kotlin.maven.PluginOption.<init>() -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.1.51:compile (compile) on project: Unable to parse configuration of mojo org.jetbrains.kotlin:kotlin-maven-plugin:1.1.51:compile for parameter pluginOption: Cannot create instance of class org.jetbrains.kotlin.maven.PluginOption
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.jetbrains.kotlin:kotlin-maven-plugin:1.1.51:compile for parameter pluginOption: Cannot create instance of class org.jetbrains.kotlin.maven.PluginOption
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:662)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:594)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot create instance of class org.jetbrains.kotlin.maven.PluginOption
	at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:147)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:54)
	at org.codehaus.plexus.component.configurator.converters.composite.AbstractCollectionConverter.fromChildren(AbstractCollectionConverter.java:54)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:68)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:268)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:210)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:632)
	... 24 more
Caused by: java.lang.InstantiationException: org.jetbrains.kotlin.maven.PluginOption
	at java.lang.Class.newInstance(Class.java:427)
	at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:143)
	... 32 more
Caused by: java.lang.NoSuchMethodException: org.jetbrains.kotlin.maven.PluginOption.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 33 more
```

In the mojo, the parameter is clearly defined, and is clearly a list of strings, though in the documentation for it, the list items of `<pluginOptions>` are `<option>` instead of `<pluginOption>`.

```
    /**
     * A list of plugin options in format (pluginId):(parameter)=(value)
     */
    @Parameter
    private List<String> pluginOptions;
```

```
    - <<:         *kotlin
      artifactId: kotlin-maven-plugin
      dependencies:
        - { <<: *kotlin, artifactId: kotlin-maven-allopen }
      executions:
        - id:    compile
          phase: compile
          goals: [ compile ]
          configuration:
            compilerPlugins: [ all-open ]
            pluginOptions:
              - all-open:annotation=javax.enterprise.context.ApplicationScoped
        - { id: test-compile, phase: test-compile, goals: [ test-compile ] }
```

Moving the configuration to the plugin declaration doesn't change anything, nor does making it a string, and/or annotating it with `!!str`.

I would have raised this with the plugin authors, but since there aren't any other complaints about this specific issue, and no plugin code is referenced in the stacktrace (apart from the `PluginOption` class), it makes more sense that this is an issue with maven misinterpreting the parameter.

**Comment by Tzrlk** [comment]
Link to plugin usage documentation: https://kotlinlang.org/docs/reference/compiler-plugins.html

**Comment by Tzrlk** [comment]
Using the translate plugin, I was able to determine that using `<pluginOption>` as the element name causes the exact same issue, and switching it to `<option>` fixes that. Obviously, this means that polyglot-yaml isn't to blame for the problem, though it raises a follow-up question which I'll raise as a separate ticket.
