### ISSUE TITLE
JRuby dialect with Java 11

### ISSUE THREAD

**Issue by mosabua** [takari/polyglot-maven#204]
I would like to get the project to work with Java 11 going forward. Currently it fails with 

```
[INFO] 
[INFO] ------------------< io.takari.polyglot:polyglot-ruby >------------------
[INFO] Building Polyglot :: Ruby 0.4.5-SNAPSHOT                          [5/13]
[INFO] -----------------------------[ takari-jar ]-----------------------------
Downloading from mavengems: mavengem:https://rubygems.org/rubygems/virtus/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/rubygems/virtus/maven-metadata.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.ChannelDescriptor (file:/home/manfred/.m2/repository/org/jruby/jruby-core/1.7.19/jruby-core-1.7.19.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.ChannelDescriptor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenSSL::X509::StoreError: setting default path failed: No password supplied for PKCS#12 KeyStore.
  set_default_paths at org/jruby/ext/openssl/X509Store.java:165
         SSLContext at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:31
                SSL at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22
            OpenSSL at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21
             (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20
               load at org/jruby/RubyKernel.java:1087
             (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-internal.rb:1
            require at org/jruby/RubyKernel.java:1071
            require at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
au1;3ltMetadataResolver.java:573)oader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jruby.embed.EvalFailedException: (OpenSSL::X509::Store4mINFO] Polyglot :: Ruby ................................... FAILURE [  8.352 s]
[INFO] Polyglot :: Scala .................................. SKIPPEDy/shared/rubygems/core_ext/kernel_require.rb:53
[INFO] Polyglot :: Groovy ................................. SKIPPEDy/shared/jopenssl19/openssl.rb:21
[INFO] Polyglot :: YAML ................................... SKIPPED
[INFO] Polyglot :: Clojure ................................ SKIPPEDy/shared/rubygems/core_ext/kernel_require.rb:55
[INFO] Polyglot :: XML .................................... SKIPPEDy/shared/rubygems/core_ext/kernel_require.rb:53
Error) setting default path failed: No password supplied for PKCS#12 KeyStore.penssl/load.rb:1
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1340)s/core_ext/kernel_require.rb:55
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1333)e_ext/kernel_require.rb:53
        at org.[INFO] Polyglot :: Java ................................... SKIPPEDsl/load.rb:24
[INFO] Polyglot :: Kotlin ................................. SKIPPED
[INFO] Polyglot :: Translate Plugin ....................... SKIPPEDy/shared/rubygems/core_ext/kernel_require.rb:55
[INFO] ------------------------------------------------------------------------ygems/core_ext/kernel_require.rb:53
[INFO] BUILD FAILUREat uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:15 minassloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
[INFO] Finished at: 20sonatype.nexus.ruby.DefaultRubygemsGateway.<init>(DefaultRubygemsGateway.java:43)quire.rb:53
        at org.torquebox.mojo.mavengem.Rubygems.<clinit>(Rubygems.java:27)d/openssl.rb:1
        ... 20 more at org/jruby/RubyKernel.java:1071
Caused by: org.jruby.exceptions.RaiseException: (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore.
        at org.jruby.ext.openssl.X509Store.set_default_paths(org/jruby/ext/openssl/X509Store.java:165)equire.rb:53
        at RUBY.SSLContext(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ss19-12-05T09:32:15-08:00
[INFO] ------------------------------------------------------------------------
l-internal.rb:31)re at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
        at RUBY.SSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22):53
        at RUBY.OpenSSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21)
[Excp[1;at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20)ta-Resolv-er--0--0" 
java.[anat org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1087)
mI      at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-in---------------------------------------------------
constituent[0]: file:/opt/tools/apache-maven-3.6.3/conf/logging/onnect(MavenGemURLConnection.java:103)
constituent[1]: file:/opt/tools/apache-maven-3.6.3/lib/maven-plugin-api-3.6.3.jarGactoemUrRLConnec tionS.java:83)
constituent[2]: file:/opt/tools/apache-maven-3.6.3/lib/maven-compat-3.6.3.jar.fillInputData(MavenGemWagon.java::51)
constituent[3]: file:/opt/tools/apache-maven-3.6.3/lib/maven-resolver-util-1.4.1.jar6)
constituent[4]: file:/opt/tools/apache-maven-3.6.3/lib/plexust-cernomal.probn:ent-annotat1)ions-2.1.0.ja
r       at org.apache.maaven.wagon.StreamWatgon.get(SotreamWagon.java:61)
c       at org.jrubyons.RubyKernel.retituent[5]: file:/opt/tools/apache-maven-3.6.3/lib/mavequire(org/jruby/n-settings-builder-3.6.3.jaRubyKernel.java:r
const1ituent[6]: 0file:/opt/tools/apache-maven-3.6.3/lib/plexus-cipher-1.77.jarTNransporter.java:43A5)
constituent[7]: file:/opt/tools/apache-maven-3.6.3/lib/plexus-int1erpolation-1.25.jarava:412)
constituen)t[8]: filse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTasPSk(BasicRepositoryConHnector.java:457)
e:/opt/tools/apache-maven-3.6.3/lib/maven-resolver-spi-1.4.1.jar
constituent[9]: file:/opt/tools/apache-maven-3.6.3/lib/guice-4.2.1-no_aop.jar
coat Kernel.require(uri:classloader:/META-INF/jruby.honstituent[10]: fimele:/opt/tools/apache-maven-3.6.3/lib/maven-artifact-3.6.3.jar
constituent[11]: file:/opt/tools/apache-mave/n-3.6.3/lib/maven-resolver-provider-3.l6.3.jar........ SUCCESS [ 39.674itoryConne s]
conistituebnt[12]: file:/opt/tools//apache-mrubavy/en-3.6s.3/lib/cdhai-api-1.0.jar
rconstituent[13]: file:/opte/tools/apache-maven-3.6.3/lib/maven-slf4j-pdrovider-3.6.3.jarESS [ 11.510 s]
constituent[14]: file:/opt/t/rubygems/coreoo_ls/apache-maven-3.6.3/lib/pleexus-utilsxt/k-3.e2.1.jarr
constituent[15]: file:/opt/tools/apache-maven-3.6.3/lib/plneel_require.rb:55)Executor.execute(BasicRepositoryConnector.java:644)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/sharexus-sec-dispatchd/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/er-1.4.jarO] Polyglot :: Maven Plugin ........................... SUCCESS [  6.026 s]
constituent[16]: file:/opt/tools/apache-maven-3.6.3/lib/maven-repository-metadata-3.6.3.jar
constituent[17]: file:/opt/tools/apache-maven-3.6.3/lib/commons-cli-1.4.jar
constituent[1o8]: fipenle:/opts/tosl/ossll-s/aipache-maven-3.6nternal.rb:4)
        at org.jru.b3/lib/maveny-resolv.RubyeKrer-transport-wagon-1.4.1.jar
constituent[19]: file:/opt/tools/apache-maven-3.6.n3/lib/commons-io-2.el5.jar
constituent[20]: file:/opt/too.lolas/apadche(-maven-3.6.3/lib/jansi-1.1o7.1.jar
constituenrg/jrt[2uby/R1]: file:/opt/tools/apache-maven-3.6.3/lib/maven-model-builder-3.6.3.jar
ubyKernconstituent[22]: file:/opt/tools/apache-maven-3.6.3/lieb/mavenl-embedder-3.6.3.ja.r
constituent[23]: file:/ojavap:t/10tools/apa8che-maven-3.67.3/lib/wagon-fi)
        le-3.3.4.at RUBY.(root)(uri:classloader:/META-INF/jruby.home/jlarib
/constituent[24]r: file:/opt/tools/aupache-mbyaven-3.6.3/lib/org./eclipse.sisu.inject-0.3.4.jar
constituent[25]: file:/opt/tools/apache-maven-3.6.3/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[26]: file:/opt/tools/apache-maven-3.6.3/lib/maven-settingshared/jopenssl19/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/rus-3.6.3.jar
constituent[27]: file:/opt/tools/apache-maven-3.6.3/lib/maven-model-3.6.3.jar
constituent[28]: file:/opt/tools/apache-maven-3.6.3/lib/maven-resolver-api-1.4.1.jar
constituent[29]: file:/opt/tools/apache-maven-3.6.3/lib/jcl-over-slf4j-1.7.29.jar
constituent[30]: fileby/shared/jopenssl19/openssl.rb:21)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classl:/opt/tools/apache-maven-3.6.3/lib/wagon-http-oader:/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:24)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META3.3.4-shaded.jar
constituent[31]-:I Nfile:F/opt/tools/apache-/jruby.home/lib/rubmavey/shna-3.6.3red/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shar/elib/ordg.ecl/ipse.sisrubygu.plexus-0.3.4.jar
econstituent[32ms/core_ext/]: file:/opt/tools/apache-maven-3.6.3/lib/slf4j-api-1.7.29.jar
constituent[33]: file:/opt/tools/apache-maven-3.6.3/lib/maven-builder-support-3.6.3.jar
constituent[34]: file:/opt/tools/apache-maven-3.6.3/lib/jsoup-1.12.1.jar
constitkernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKuent[35]: file:/opt/tools/apache-maven-3.6.3/lib/wagon-provider-api-3.3.4.jar
constituent[36]: file:/opt/tools/apache-maven-3.6.3/lib/mavenernel.java:1071)
        at Kernel.require(uri:classlo-ader:/METAshared-utils-3.2.1.jar
constituent[37]: file:/opt/tools/apache-maven-3.6.3/lib/maven-resolver-impl-1.4.1.jar
constituent[38]: file:/opt/tools/apache-maven-3.6.3/lib/maven-core-3.6.3.jar
constituent[39]: file:/opt/tools/apache-maven-3.6.3/lib/javax.inject-1.jar
constituent[40]: file:/opt/tools/apache-maven-3.6.3/lib/commons-lang3-3.8.1.jar
constituent[41]: file:/opt/tools/apache-maven-3.6.3/lib/guava-25.1-android.jar
constituent[42]: file:/opt/tools/apache-maven-3.6.3/lib/jsr250-api-1.0.jar
---------------------------------------------------
-INF/jruby.home/liException in thread "main" b/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/security.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/security.rb:11)
java.lang.ExceptionInInitializerError
        at org.torquebox.mojo.mavengem.RubygemsFactory.getOrCreate(RubygemsFactory.java:116)
        at org.torquebox.mojo.mavengem.MavenGemURLConnection.connect(MavenGemURLConnection.java:103)
        at org.torquebox.mojo.mavengem.MavenGemURLConnection.getInputStream(MavenGemURLConnection.java:83)
        at org.torquebox.mojo.mavengem.wagon.MavenGemWagon.fillInputData(MavenGemWagon.java:51)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:644)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:235)
        at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:573)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jruby.embed.EvalFailedException: (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore.
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1340)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1333)
        at org.sonatype.nexus.ruby.DefaultRubygemsGateway.<init>(DefaultRubygemsGateway.java:43)
        at org.torquebox.mojo.mavengem.Rubygems.<clinit>(Rubygems.java:27)
        ... 20 more
Caused by: org.jruby.exceptions.RaiseException: (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore.
        at org.jruby.ext.openssl.X509Store.set_default_paths(org/jruby/ext/openssl/X509Store.java:165)
        at RUBY.SSLContext(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:31)
        at RUBY.SSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22)
        at RUBY.OpenSSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1087)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-internal.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-internal.rb:4)
        at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1087)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl.rb:21)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:24)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/security.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
        at Kernel.require(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/rubygems/security.rb:11)
```

**Comment by mosabua** [comment]
I have not looked at all ... just in general though ... do we expect JRuby, ruby-maven and the polyglot ruby dialect to work with Java 11 .. I assume yes ... but dont know yet where to look first to update. Any tips @mkristian @headius and others

**Comment by headius** [comment]
First off this should be updated to the latest JRuby, 9.2.9.0. The build shown above is running JRuby 1.7.x, which has never been supported on Java 11.

If 9.2.9.0 still has issues we can address those in turn.

**Comment by mosabua** [comment]
For some weird reason it now works.. not sure what I had going there. Will look further and file new issues if I run into any headaches.
