### ISSUE TITLE
dependencies section inside build->plugins throws ClassCastException

### ISSUE THREAD

**Issue by zxiiro** [takari/polyglot-maven#43]
Using the following pom.yml section we get a ClassCastException if we try to use dependencies inside of a plugin.

<pre>
profiles:
      build:
        plugins:
            - groupId: org.apache.maven.plugins
              artifactId: maven-site-plugin
              version: 3.4
              dependencies:
                - {artifactId: wagon-webdav-jackrabbit, groupId: org.apache.maven.wagon, optional: false,
        type: jar, version: '2.9'}
</pre>

<pre>
[ERROR] Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.apache.maven.model.Dependency
        at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writePlugin(MavenXpp3Writer.java:1402)
        at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writeBuildBase(MavenXpp3Writer.java:400)
        at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writeProfile(MavenXpp3Writer.java:1583)
        at org.apache.maven.model.io.xpp3.MavenXpp3Writer.writeModel(MavenXpp3Writer.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3Writer.write(MavenXpp3Writer.java:100)
        at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:106)
        at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:83)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:529)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:269)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
</pre>

**Comment by mosabua** [comment]
Closing this issue. Please try again with the new 0.3.0 release and file an updated ticket if desired.
